events_controllers:
    resource:
        path: ../src/Events/Presentation/Http
        namespace: App\Events\Presentation\Http
    type: attribute

organisers_controllers:
    resource:
        path: ../src/Organisers/Presentation/Http
        namespace: App\Organisers\Presentation\Http
    type: attribute

tickets_controllers:
    resource:
        path: ../src/Tickets/Presentation/Http
        namespace: App\Tickets\Presentation\Http
    type: attribute

auth_controllers:
    resource:
        path: ../src/Auth/Presentation/Http
        namespace: App\Auth\Presentation\Http
    type: attribute
