controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

events_controllers:
    resource:
        path: ../src/Events/Presentation/Http
        namespace: App\Events\Presentation\Http
    type: attribute

